[theme]
base = "dark"
primaryColor = "#22D3EE"
backgroundColor = "#0F1115"
secondaryBackgroundColor = "#171923"
textColor = "#E5E7EB"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showSidebarNavigation = false